services:

  db:
    container_name: mariadb-11.4.5-ubi9
    image: mariadb:11.4.5-ubi9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3309:3306
      -
  adminer:
    container_name: adminer-4.17.1
    image: adminer:4.17.1
    restart: always
    ports:
      - 8082:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 5000:80
      - 1025:25